# rbenv for ruby
if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi

# pyenv for python
# if which pyenv > /dev/null; then eval "$(pyenv init -)"; fi

# Config JAVA
# export JAVA_HOME=$(/usr/libexec/java_home)

# NVM
export NVM_DIR=~/.nvm
source $(brew --prefix nvm)/nvm.sh
