export ZSH=$HOME/.oh-my-zsh

# ZSH Base configuration

ZSH_THEME="ys"
HYPHEN_INSENSITIVE="true"

export LANG=en_US.UTF-8

# User configuration
plugins=(osx git zsh-completions zsh-syntax-highlighting aws rbenv ruby rails pyenv python pip bundler gem brew node npm yarn web-search)

# Library

# Homebrew
export PATH="/usr/local/sbin:$PATH"

# Development

# rbenv for ruby
if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi

# pyenv for python
# if which pyenv > /dev/null; then eval "$(pyenv init -)"; fi

# Config JAVA
# export JAVA_HOME=$(/usr/libexec/java_home)

# NVM
export NVM_DIR=~/.nvm
source $(brew --prefix nvm)/nvm.sh

# Homebrew ZSH Autocomplete
if type brew &>/dev/null; then
  FPATH=$(brew --prefix)/share/zsh/site-functions:$FPATH

  FPATH=(/usr/local/share/zsh-completions $fpath)
fi

# zsh-completions
autoload -U compinit && compinit

# zsh-syntax-highlighting
source /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

source $ZSH/oh-my-zsh.sh

# Another Library

# Python Lib
# export PATH="/Users/nijicha/.local/bin:$PATH"

# alias
alias hyperconfig="code ~/.zshrc && code ~/.hyper.js"
alias nginxconfig="code /usr/local/etc/nginx/nginx.conf"
alias fix_maria_db="mkdir /usr/local/etc/my.cnf.d"

RELAUNCH_FINDER="killall Finder /System/Library/CoreServices/Finder.app"
alias show_dot_files="defaults write com.apple.finder AppleShowAllFiles YES; eval $RELAUNCH_FINDER"
alias hide_dot_files="defaults write com.apple.finder AppleShowAllFiles NO; eval $RELAUNCH_FINDER"

# Ref : https://github.com/mbadolato/iTerm2-Color-Schemes/blob/master/tools/screenshotTable.sh
function color_table {
    T='awesome'   # The test text

    echo -e "\n                 40m     41m     42m     43m\
        44m     45m     46m     47m";

    for FGs in '    m' '   1m' '  30m' '1;30m' '  31m' '1;31m' '  32m' \
            '1;32m' '  33m' '1;33m' '  34m' '1;34m' '  35m' '1;35m' \
            '  36m' '1;36m' '  37m' '1;37m';
    do FG=${FGs// /}
    echo -en " $FGs \033[$FG  $T  "
    for BG in 40m 41m 42m 43m 44m 45m 46m 47m;
        do echo -en "$EINS \033[$FG\033[$BG  $T  \033[0m";
    done
    echo;
    done
    echo
}
