- name: Copy misc to .dotfiles
  copy:
    src: misc
    dest: ~/.dotfiles
    force: yes

- name: Link mybashrc
  file:
    src: ~/.dotfiles/misc/.mybashrc
    path: ~/.mybashrc
    state: link
    force: yes

- name: Link zshrc
  file:
    src: ~/.dotfiles/misc/zshrc
    path: ~/.zshrc
    state: link
    force: yes

- name: Link vimrc
  file:
    src: ~/.dotfiles/misc/vimrc
    path: ~/.vimrc
    state: link
    force: yes

- name: Link gitconfig
  file:
    src: ~/.dotfiles/misc/git/gitconfig
    path: ~/.gitconfig
    state: link
    force: yes

- name: Link gitignore_global
  file:
    src: ~/.dotfiles/misc/git/gitignore_global
    path: ~/.gitignore_global
    state: link
    force: yes
